workspace:
  base: /go/src
  path: github.com/crusttech/crust

kind: pipeline
name: docker image build

steps:
- name: unit-tests
  image: cortezaproject/corteza-server-builder:latest
  pull: always
  environment:
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
    CI: circleci
  commands:
    - make test

- name: crust-server-system
  image: plugins/docker
  depends_on: [ 'unit-tests' ]
  settings:
    repo: crusttech/crust-server-system
    auto_tag: true # generate tag names automatically based on git branch and git tag
    dockerfile: Dockerfile.crust-server-system
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password


- name: crust-server-compose
  image: plugins/docker
  depends_on: [ 'unit-tests' ]
  settings:
    repo: crusttech/crust-server-compose
    auto_tag: true # generate tag names automatically based on git branch and git tag
    dockerfile: Dockerfile.crust-server-compose
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password

- name: crust-server-messaging
  depends_on: [ 'unit-tests' ]
  image: plugins/docker
  settings:
    repo: crusttech/crust-server-messaging
    auto_tag: true # generate tag names automatically based on git branch and git tag
    dockerfile: Dockerfile.crust-server-messaging
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password


- name: crust-server
  image: plugins/docker
  depends_on: [ 'unit-tests' ]
  settings:
    repo: crusttech/crust-server
    auto_tag: true # generate tag names automatically based on git branch and git tag
    dockerfile: Dockerfile.crust-server
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_password

trigger:
  branch:
    - master
  refs:
    - refs/tags/v20??.*
  event:
    - push
