kind: pipeline
name: Build
type: docker

steps:
  - name: "Build release (tag)"
    image: cortezaproject/corteza-server-builder:latest
    environment:
      RELEASE_SFTP_KEY: { from_secret: RELEASE_SFTP_KEY }
      RELEASE_SFTP_URI: { from_secret: RELEASE_SFTP_URI }
    commands:
    - make release-clean release -j4 BUILD_OS=linux BUILDARCH=amd64 BUILD_VERSION=${DRONE_TAG}
#    - make release-clean release -j4 BUILD_OS=darwin BUILDARCH=amd64 BUILD_VERSION=${DRONE_TAG}
#    - make release-clean release -j4 BUILD_OS=windows BUILDARCH=amd64 BUILD_VERSION=${DRONE_TAG}
    - make upload
    when:
      event: [ tag ]
      ref:
      - refs/tags/20??.3.*
      - refs/tags/20??.6.*
      - refs/tags/20??.9.*
      - refs/tags/20??.12.*

  - name: "Build unstable release (develop)"
    image: cortezaproject/corteza-server-builder:latest
    environment:
      RELEASE_SFTP_KEY: { from_secret: RELEASE_SFTP_KEY }
      RELEASE_SFTP_URI: { from_secret: RELEASE_SFTP_URI }
    commands:
    - make release-clean release -j4 BUILD_OS=linux BUILDARCH=amd64 BUILD_VERSION=unstable
    - make upload
    when:
      event: [ push ]
      branch: [ develop ]
